/* Exercise catalog.
   Seeded from exercises.json, plus the Workout A/B/C movements from
   PF_Workout_Plan.txt categorised by the muscle they train.
   Maintained by hand - add new exercises in their group block. */
const EXERCISE_CATALOG = [
  // Chest
  { group: "Chest", name: "Bench Press" },
  { group: "Chest", name: "Cross-body Raise" },
  { group: "Chest", name: "Decline Bench Press" },
  { group: "Chest", name: "Floor Press" },
  { group: "Chest", name: "Incline Bench Press" },
  { group: "Chest", name: "Machine Chest Press" },
  { group: "Chest", name: "Overhead Pull Over" },
  { group: "Chest", name: "Pec Deck Fly" },
  { group: "Chest", name: "Prone Chest Fly" },
  { group: "Chest", name: "Smith Machine Incline Press" },
  { group: "Chest", name: "Standing Chest Fly" },
  // Back
  { group: "Back", name: "Back Extension" },
  { group: "Back", name: "Barbell Row" },
  { group: "Back", name: "Bent Over Row" },
  { group: "Back", name: "Chest-Supported Row Machine" },
  { group: "Back", name: "Chin Up" },
  { group: "Back", name: "Deadlift" },
  { group: "Back", name: "Lat Pulldown" },
  { group: "Back", name: "Overhand Lat Pulldown" },
  { group: "Back", name: "Pull-up" },
  { group: "Back", name: "Seated Row" },
  { group: "Back", name: "Shrug" },
  { group: "Back", name: "Single Arm Row" },
  { group: "Back", name: "Single-Arm Cable Row" },
  { group: "Back", name: "Straight Arms Pushdown" },
  { group: "Back", name: "Underhand Lat Pulldown" },
  { group: "Back", name: "Upright Row" },
  { group: "Back", name: "Wide Grip Row" },
  // Shoulders
  { group: "Shoulders", name: "Cable Lateral Raise" },
  { group: "Shoulders", name: "External Shoulder Rotation" },
  { group: "Shoulders", name: "Face Pull" },
  { group: "Shoulders", name: "Front Raise" },
  { group: "Shoulders", name: "Internal Shoulder Rotation" },
  { group: "Shoulders", name: "Lateral Raise" },
  { group: "Shoulders", name: "Overhead Press" },
  { group: "Shoulders", name: "Reverse Pec Deck (Rear Delts)" },
  { group: "Shoulders", name: "Seated Dumbbell Shoulder Press" },
  { group: "Shoulders", name: "Shoulder Press" },
  // Arms
  { group: "Arms", name: "Cable Curl (Straight or EZ Bar)" },
  { group: "Arms", name: "Close Grip Bench Press" },
  { group: "Arms", name: "Close Grip Curl" },
  { group: "Arms", name: "Dumbbell Curl" },
  { group: "Arms", name: "Dumbbell Hammer Curl" },
  { group: "Arms", name: "Hammer Curl" },
  { group: "Arms", name: "Incline Curl" },
  { group: "Arms", name: "Normal Curl" },
  { group: "Arms", name: "Overhead Cable Triceps Extension" },
  { group: "Arms", name: "Overhead Tricep Extension" },
  { group: "Arms", name: "Preacher Curl" },
  { group: "Arms", name: "Reverse Curl" },
  { group: "Arms", name: "Rope Triceps Pushdown" },
  { group: "Arms", name: "Single Arm Curl" },
  { group: "Arms", name: "Single Arm Hammer Curl" },
  { group: "Arms", name: "Skull Crusher" },
  { group: "Arms", name: "Spider Curl" },
  { group: "Arms", name: "Tricep Extension" },
  { group: "Arms", name: "Tricep Kickback" },
  { group: "Arms", name: "Tricep Pushdown" },
  { group: "Arms", name: "Tricep Pushdown (Bar)" },
  { group: "Arms", name: "Tricep Pushdown (Rope)" },
  { group: "Arms", name: "Wide Grip Curl" },
  // Forearms
  { group: "Forearms", name: "Bar Hang" },
  { group: "Forearms", name: "Wrist Curl" },
  { group: "Forearms", name: "Wrist Curl BTB" },
  { group: "Forearms", name: "Wrist Curl Extension" },
  // Legs
  { group: "Legs", name: "Back Squat" },
  { group: "Legs", name: "Bulgarian Split Squat" },
  { group: "Legs", name: "Calf Raise" },
  { group: "Legs", name: "Calf Raise on Leg Press" },
  { group: "Legs", name: "Front Squat" },
  { group: "Legs", name: "Goblet Squat" },
  { group: "Legs", name: "Hip Thrust" },
  { group: "Legs", name: "Landmine Squat" },
  { group: "Legs", name: "Leg Extension" },
  { group: "Legs", name: "Leg Press" },
  { group: "Legs", name: "Lunge" },
  { group: "Legs", name: "Lying or Seated Leg Curl" },
  { group: "Legs", name: "Romanian Deadlift" },
  { group: "Legs", name: "Single Leg Calf Raise" },
  { group: "Legs", name: "Single Leg RDL" },
  { group: "Legs", name: "Smith Machine or DB Romanian Deadlift" },
  { group: "Legs", name: "Smith Machine Squat" },
  { group: "Legs", name: "Squat" },
  { group: "Legs", name: "Step Up" },
  // Cardio
  { group: "Cardio", name: "Treadmill Walk" },
  { group: "Cardio", name: "Treadmill Run" },
  { group: "Cardio", name: "Dog Walking" },
  { group: "Cardio", name: "Exercise Bike" },

];
