/* Exercise catalog.
   Seeded from exercises.json, plus the Workout A/B/C movements from
   PF_Workout_Plan.txt categorised by the muscle they train.
   `notes` are execution/setup cues shown wherever the exercise appears -
   the session page, the workout list, and the Exercises library.
   Maintained by hand - add new exercises in their group block. */
const EXERCISE_CATALOG = [
  // Chest
  { group: "Chest", name: "Bench Press" },
  { group: "Chest", name: "Cross-body Raise" },
  { group: "Chest", name: "Decline Bench Press" },
  { group: "Chest", name: "Floor Press" },
  { group: "Chest", name: "Incline Bench Press" },
  { group: "Chest", name: "Machine Chest Press", notes: "Handles aligned with mid-chest. Full stretch at the bottom, don't slam the stack." },
  { group: "Chest", name: "Overhead Pull Over" },
  { group: "Chest", name: "Pec Deck Fly", notes: "Squeeze 1 second at peak contraction. Pump finisher." },
  { group: "Chest", name: "Prone Chest Fly" },
  { group: "Chest", name: "Smith Machine Incline Press", notes: "Bench at 30°. Bar to upper chest, 3-second lowering, drive up explosively." },
  { group: "Chest", name: "Standing Chest Fly" },
  // Back
  { group: "Back", name: "Back Extension" },
  { group: "Back", name: "Barbell Row" },
  { group: "Back", name: "Bent Over Row" },
  { group: "Back", name: "Chest-Supported Row Machine", notes: "Chest glued to the pad. Drive elbows back, squeeze shoulder blades." },
  { group: "Back", name: "Chin Up" },
  { group: "Back", name: "Deadlift" },
  { group: "Back", name: "Lat Pulldown", notes: "Slightly wider than shoulder grip, pull to upper chest. Stack maxed? Add a 2-second pause." },
  { group: "Back", name: "Overhand Lat Pulldown" },
  { group: "Back", name: "Pull-up" },
  { group: "Back", name: "Seated Row" },
  { group: "Back", name: "Shrug" },
  { group: "Back", name: "Single Arm Row" },
  { group: "Back", name: "Single-Arm Cable Row", notes: "Full stretch forward, then row to the hip." },
  { group: "Back", name: "Straight Arms Pushdown" },
  { group: "Back", name: "Underhand Lat Pulldown" },
  { group: "Back", name: "Upright Row" },
  { group: "Back", name: "Wide Grip Row" },
  { group: "Back", name: "Face Pull"},
  // Shoulders
  { group: "Shoulders", name: "Cable Lateral Raise", notes: "Lowest pulley, lean slightly away. Lead with the elbow." },
  { group: "Shoulders", name: "External Shoulder Rotation" },
  { group: "Shoulders", name: "Face Pull" },
  { group: "Shoulders", name: "Front Raise" },
  { group: "Shoulders", name: "Internal Shoulder Rotation" },
  { group: "Shoulders", name: "Lateral Raise" },
  { group: "Shoulders", name: "Overhead Press" },
  { group: "Shoulders", name: "Reverse Pec Deck (Rear Delts)", notes: "Palms down or neutral. High reps, no swinging." },
  { group: "Shoulders", name: "Seated Dumbbell Shoulder Press", notes: "Bench at 85–90°. At max DB weight, switch to 4-second negatives." },
  { group: "Shoulders", name: "Shoulder Press" },
  { group: "Shoulders", name: "Machine Shoulder Press"},
  // Arms
  { group: "Biceps", name: "Cable Curl (Straight or EZ Bar)", notes: "Elbows slightly in front of the body, full range." },
  { group: "Triceps", name: "Close Grip Bench Press" },
  { group: "Biceps", name: "Close Grip Curl" },
  { group: "Biceps", name: "Dumbbell Curl" },
  { group: "Biceps", name: "Dumbbell Hammer Curl", notes: "Neutral grip, controlled. Builds brachialis and grip." },
  { group: "Biceps", name: "Rope Hammer Curl" },
  { group: "Biceps", name: "Incline Curl" },
  { group: "Biceps", name: "Normal Curl" },
  { group: "Triceps", name: "Overhead Cable Triceps Extension", notes: "Face away from the stack, hinge slightly forward. Full stretch on the long head." },
  { group: "Triceps", name: "Overhead Tricep Extension" },
  { group: "Biceps", name: "Preacher Curl" },
  { group: "Biceps", name: "Reverse Curl" },
  { group: "Triceps", name: "Rope Triceps Pushdown", notes: "Elbows pinned to your sides, spread the rope at the bottom." },
  { group: "Biceps", name: "Single Arm Curl" },
  { group: "Biceps", name: "Single Arm Hammer Curl" },
  { group: "Triceps", name: "Skull Crusher" },
  { group: "Biceps", name: "Spider Curl" },
  { group: "Triceps", name: "Tricep Extension" },
  { group: "Triceps", name: "Tricep Kickback" },
  { group: "Triceps", name: "Tricep Pushdown" },
  { group: "Triceps", name: "Tricep Pushdown (Bar)" },
  { group: "Triceps", name: "Tricep Pushdown (Rope)" },
  { group: "Biceps", name: "Wide Grip Curl" },
  { group: "Biceps", name: "Machine Preacher Curl"},
  { group: "Triceps", name: "Machine Triceps Pushdown"},
  // Forearms
  { group: "Forearms", name: "Bar Hang" },
  { group: "Forearms", name: "Wrist Curl" },
  { group: "Forearms", name: "Wrist Curl BTB" },
  { group: "Forearms", name: "Wrist Curl Extension" },
  // Legs
  { group: "Legs", name: "Back Squat" },
  { group: "Legs", name: "Bulgarian Split Squat" },
  { group: "Legs", name: "Calf Raise" },
  { group: "Legs", name: "Calf Raise (Leg Press)", notes: "Full stretch at the bottom with a 2-second pause. No bouncing." },
  { group: "Legs", name: "Front Squat" },
  { group: "Legs", name: "Goblet Squat" },
  { group: "Legs", name: "Hip Thrust" },
  { group: "Legs", name: "Landmine Squat" },
  { group: "Legs", name: "Leg Extension", notes: "1-second squeeze at the top. Toes slightly out hits the inner quad." },
  { group: "Legs", name: "Leg Press", notes: "Feet mid-platform, shoulder width. Stack maxed? 2-second pause at the bottom." },
  { group: "Legs", name: "Lunge" },
  { group: "Legs", name: "Seated Leg Curl", notes: "Slow eccentric. Don't let the pad crash back down." },
  { group: "Legs", name: "Romanian Deadlift" },
  { group: "Legs", name: "Single Leg Calf Raise" },
  { group: "Legs", name: "Single Leg RDL" },
  { group: "Legs", name: "Smith Machine or DB Romanian Deadlift", notes: "Soft knees, hips back, 3–4 second lowering. Bar stays close to your legs." },
  { group: "Legs", name: "Smith Machine Squat", notes: "Feet slightly forward of the bar path. Control the descent to just below parallel." },
  { group: "Legs", name: "Squat" },
  { group: "Legs", name: "Step Up" },
  { group: "Legs", name: "Seated Calf Raise"},
  // Cardio
  { group: "Cardio", name: "Treadmill Walk" },
  { group: "Cardio", name: "Treadmill Run" },
  { group: "Cardio", name: "Dog Walking" },
  { group: "Cardio", name: "Exercise Bike" },
  { group: "Cardio", name: "Rowing Machine"},
  { group: "Cardio", name: "Stair Climber"},
  { group: "Cardio", name: "Elliptical Trainer"}
];
